### ISSUE TITLE
install/java problem in Ubuntu 20.04

### ISSUE THREAD

**Issue by paul-manchester** [koadman/mauve#3]
Hi 

Im having a problem with 2.4.0, 2.3.1 and other installs on Ubuntu 20.04 using openjdk 11 or 14 and oracle 11

calling ./Mauve always returns:

Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "."
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:654)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.gel.mauve.gui.Mauve.hasRequiredJVM(Unknown Source)
	at org.gel.mauve.gui.Mauve.init(Unknown Source)
	at org.gel.mauve.gui.Mauve$2.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I cant seem to get around this - any ideas? I have messed around with the java path in the script - no differences. Am I missing some version or dependency?

best

Paul

**Comment by JFsanchezherrero** [comment]
Hi there,

I got the same issue and I followed the advice here (https://www.biostars.org/p/9498908/) and it worked.

I installed java-jdk from here (https://anaconda.org/bioconda/java-jdk).

I am having other issues with `mauve` right now so it is taking time to see if it finally fits what I want to test.

Best regards,
Jose F.
